# Generated by Django 3.1.5 on 2021-02-27 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210226_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='poster',
            new_name='creator',
        ),
    ]
