# Generated by Django 3.1.5 on 2021-03-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20210306_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumeEngTitle', models.CharField(max_length=150)),
            ],
        ),
    ]
