# Generated by Django 3.1.5 on 2021-03-08 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_volume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Volume',
        ),
    ]
