# Generated by Django 3.1.5 on 2021-01-12 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210111_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='listing',
            new_name='auction',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='current_price',
        ),
        migrations.AddField(
            model_name='listing',
            name='highest_bid',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='winner',
            field=models.OneToOneField(default=None, null=True, on_delete=models.SET("Winners's account got deleted"), related_name='auctions_won', to=settings.AUTH_USER_MODEL),
        ),
    ]
